baseURL: '/'
title: 'De Grote Eik'
theme: 'binario'
sectionPagesMenu: main
params:
  mainSections:
  - visie
  - frog-garden
  - gallery
  - contact
  colorTheme: 'dark-green'
  breadcrumb:
    enable: true
